# Generated by Django 4.2.23 on 2025-12-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_userextra_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Process",
            fields=[
                ("process_id", models.AutoField(primary_key=True, serialize=False)),
                ("process_name", models.CharField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
