# Generated by Django 4.2.23 on 2025-12-07 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_process"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubProcess",
            fields=[
                ("subprocess_id", models.AutoField(primary_key=True, serialize=False)),
                ("subprocess_name", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subprocesses",
                        to="api.process",
                    ),
                ),
            ],
        ),
    ]
