# Generated by Django 4.2.23 on 2025-12-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_subprocess"),
    ]

    operations = [
        migrations.AddField(
            model_name="userextra",
            name="assigned_processes",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="userextra",
            name="assigned_subprocesses",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
