# Generated by Django 4.2.23 on 2025-12-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_userextra_assigned_processes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subprocess",
            name="link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
