# Generated by Django 4.2.23 on 2025-12-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_objective_video_image_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="userextra",
            name="assigned_objectives",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
